//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ruleta {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class lang1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ruleta.lang1", typeof(lang1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Váš aktuálny kredit je: {0}.
        /// </summary>
        internal static string actual_credit {
            get {
                return ResourceManager.GetString("actual_credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Čierna.
        /// </summary>
        internal static string b {
            get {
                return ResourceManager.GetString("b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Čas:{0}, Vaša stávka: {1}, Výsledok =  Číslo:{2} Farba:{3} Párne:{4}, Stlpec: {6},  Záver: {5}.
        /// </summary>
        internal static string history_text {
            get {
                return ResourceManager.GetString("history_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prehra.
        /// </summary>
        internal static string loose {
            get {
                return ResourceManager.GetString("loose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zelená.
        /// </summary>
        internal static string n {
            get {
                return ResourceManager.GetString("n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stávka je napr. 
        ///sNum = Num cislo 0-36, sR = Stávka na červenú, sB = stávka na čiernu,
        ///sP = stávka na párne, sN = stávka na nepárne, cN = N=1/2/3 stávka na stlpec
        ///stávka na rozsah r1 (1-18), r2 (1-12), r3 (13-24), r4 (25-36), r5 (19-36)
        ///
        ///Veľa štastia...
        ///
        ///Vaša stávka:.
        /// </summary>
        internal static string pomoc {
            get {
                return ResourceManager.GetString("pomoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Červená.
        /// </summary>
        internal static string r {
            get {
                return ResourceManager.GetString("r", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadajte vašu voľbu (end = koniec hry, bČíslo =  Číslo je vklad napr. 100) 
        ///ak vložíte Bank už nemôžete z hry oddísť.....
        /// </summary>
        internal static string uvod {
            get {
                return ResourceManager.GetString("uvod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Číslo:{0} Farba:{1} Párne:{2} Stlpec:{3}.
        /// </summary>
        internal static string vypis_stavu {
            get {
                return ResourceManager.GetString("vypis_stavu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výhra.
        /// </summary>
        internal static string win {
            get {
                return ResourceManager.GetString("win", resourceCulture);
            }
        }
    }
}
